FROM registry.artifakt.io/symfony:4.4-apache@sha256:16d38d8d7892f9f31fef0d0804efd732c31ff61a723bc0f8c3cf2a81566f1dbf

LABEL vendor="Artifakt" \
      author="djalal@artifakt.io" \
      stage="alpha"

