FROM php:7-apache

# already installed : curl, dom, hash, ctype, iconv, mbstring, openssl, simplexml
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
        libxml2-dev \
        zlib1g-dev \
        libxslt-dev \
        libzip-dev  \
        libcurl4-openssl-dev \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-install bcmath \
    && docker-php-ext-install intl \
    && docker-php-ext-install soap \
    && docker-php-ext-install zip \
    && docker-php-ext-install xsl \
    && docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd \
    && docker-php-ext-configure mysqli --with-mysqli=mysqlnd \
    && docker-php-ext-install pdo_mysql \
    && apt-get --purge -y remove \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
        libxml2-dev \
        libxslt-dev \
        libzip-dev \
        libcurl4-openssl-dev \
        zlib1g-dev

RUN a2enmod rewrite headers ssl

COPY ./init/apache/* /etc/apache2/sites-available

RUN a2ensite slim.conf

COPY --from=composer /usr/bin/composer /usr/bin/composer

COPY composer.lock /var/www/html/composer.lock
COPY composer.json /var/www/html/composer.json

RUN apt-get update \
    && apt-get install -y git \
    && /usr/bin/composer install --ignore-platform-reqs --no-dev --no-scripts --prefer-dist \
    && apt-get remove -y --purge git

COPY --chown=www-data:www-data . /var/www/html/
#COPY --chown=www-data:www-data ./init/index.php /var/www/html/index.php
#COPY --chown=www-data:www-data ./init/.htaccess /var/www/html/.htaccess
#COPY --chown=www-data:www-data ./init/config/config.php.dist /var/www/html/application/config/config.php
#COPY --chown=www-data:www-data ./init/config/database.php.dist /var/www/html/application/config/database.php

#RUN cp -rp /var/www/html/assets/css/* /var/www/html/build

#COPY php.ini /usr/local/etc/php/

WORKDIR /var/www/html

RUN a2dissite 000-default.conf

# ERROR seems it requires root privilege to open port 80
#USER www-data

RUN php -m