parameters:
    database_host: '%env(ARTIFAKT_MYSQL_HOST)%'
    database_port: '%env(ARTIFAKT_MYSQL_PORT)%'
    database_name: '%env(ARTIFAKT_MYSQL_DATABASE_NAME)%'
    database_user: '%env(ARTIFAKT_MYSQL_USER)%'
    database_password: '%env(ARTIFAKT_MYSQL_PASSWORD)%'
    mailer_transport: 'smtp'
    mailer_host: 'localhost'
    mailer_user: 'null'
    mailer_password: 'null'
    secret: 'zQCvhDu2V9eTDD3z4PcA2ex72yTVLZnG'