  FROM registry.artifakt.io/php:7.3-apache
  
  COPY --chown=www-data:www-data . /var/www/html/
  WORKDIR /var/www/html

  # copy the artifakt folder on root
  RUN  if [ -d .artifakt ]; then cp -rp /var/www/html/.artifakt /.artifakt/; fi
  # run custom scripts build.sh
  RUN  if [ -f /.artifakt/build.sh ]; then /.artifakt/build.sh; fi
    
  RUN [ -f composer.lock ] && composer install --no-cache --optimize-autoloader --no-interaction --no-ansi --no-dev || true
