parameters:
    database_driver: pdo_mysql
    database_host: mysql
    database_port: null
    database_name: akeneo4_pim
    database_user: akeneo4_pim
    database_password: akeneo4_pim
    locale: en
    secret: ArtifaktRecommendsThisTokenChanged
    product_index_name: akeneo_pim_product
    product_model_index_name: akeneo_pim_product_model
    product_and_product_model_index_name: akeneo_pim_product_and_product_model
    index_hosts: 'elastic:changeme@elasticsearch:9200'