version: '2'

services:
  app:
    build: .
    image: registry.artifakt.io/3.2-apache
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: akeneo_pim
      MYSQL_USER: akeneo_pim
      MYSQL_PASSWORD: akeneo_pim
    env_file:
      - .env

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4'
    environment:
      ES_JAVA_OPTS: '-Xms512M -Xmx512M'
      discovery.type: 'single-node'
    ulimits:
        nofile:
           soft: 65536
           hard: 65536
