parameters:
    database_driver: pdo_mysql
    database_host: 'mysql'
    database_port: 3306
    database_name: 'akeneo5_pim'
    database_user: 'akeneo5_pim'
    database_password: 'akeneo5_pim'
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    product_index_name: akeneo_pim_product
    product_model_index_name: akeneo_pim_product_model
    product_and_product_model_index_name: akeneo_pim_product_and_product_model
    index_hosts: 'elastic:changeme@elasticsearch:9200'