on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Purge badges from camo
        run: |
          pwd
          ls -la

          PurgeBadgeList() {
              while read -t5 URL Badge; do
                  URL="${URL%\"*}";
                  Badge="'${Badge#*\"}'                                        "
                  echo -n "Purging Badge ${Badge}: ";
                  read -t60 result < <( curl --silent --request 'PURGE' -H 'Content-Type:application/json' --user-agent "$UserAgentString" --output '/dev/stdout' $URL | jq .status )
                  result="${result//\"/}"
                  echo "${result:-???}"
              done
          }
          export -f PurgeBadgeList;
          PurgeBadgeList < <(cat ./.github/workflows/PURGE.md | grep -o 'https://camo.githubusercontent.com.*alt="[^"]*')
          
